FROM python:3.12-slim
# Use light python image

# 1. Copy dependencies
COPY src/requirements.txt /tmp/requirements.txt

# 2. Install dependencies
RUN python3.12 -m pip install --no-cache-dir --upgrade pip setuptools
RUN python3.12 -m pip install --no-cache-dir --upgrade -r /tmp/requirements.txt

# 3. Install useful tools for development
RUN apt-get update -y
RUN apt-get install nano curl -y

# 4. Copy API code
COPY src /code/app

# 5. Copy testing code
COPY tests /code/tests

WORKDIR /code/app

# 5. Create a user with limited permissions
RUN addgroup --system appuser \
 && adduser  --system \
             --ingroup appuser \
             --no-create-home \
             --disabled-login \
             --gecos "" \
             appuser

# 6. Switch to user "appuser" before any subsequent build/run
USER appuser

EXPOSE 8000

CMD ["python3.12", "-m", "run"]